[project]
name = "real-estate-pricing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.133.1",
    "pandas>=3.0.1",
    "sqlalchemy>=2.0.47",
    "uvicorn>=0.41.0",
]
